import '../../models/Tour.dart';

List<Tour> toursData() {
  return [
    Tour(
      destination: "Trang An",
      location: "Ninh Binh, Vietnam",
      days: 3,
      nights: 2,
      price: 180,
      tourProvider: "Nature Escape Tours",
      tourProviderWeb: "https://natureescapetours.com",
      schedule: [
        ["8:00 AM: Arrival and hotel check-in", "10:00 AM: Boat trip in Trang An", "3:00 PM: Visit Bai Dinh Pagoda"],
        ["7:00 AM: Explore Mua Caves", "12:00 PM: Lunch at local restaurant", "3:00 PM: Cycling around Tam Coc"],
        ["8:00 AM: Breakfast and check-out", "10:00 AM: Departure"],
      ],
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTm9H1Z2CiFWMZsNPqvpQlh86ZyBoNkUe2xvQ&s",
    ),
    Tour(
      destination: "Trang An",
      location: "Ninh Binh, Vietnam",
      days: 2,
      nights: 1,
      price: 120,
      tourProvider: "Eco Tour Adventures",
      tourProviderWeb: "https://ecotouradventures.com",
      schedule: [
        ["7:00 AM: Arrival at Trang An", "10:00 AM: Visit Hoa Lu Ancient Capital", "2:00 PM: Boat ride in Tam Coc"],
        ["8:00 AM: Breakfast and hotel check-out", "10:00 AM: Visit Bich Dong Pagoda", "12:00 PM: Departure"],
      ],
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNcE993wNj-nMWhShBIS1Ni9o9hcz3vomBYg&s",
    ),
    Tour(
      destination: "Trang An",
      location: "Ninh Binh, Vietnam",
      days: 4,
      nights: 3,
      price: 250,
      tourProvider: "Heritage Journey",
      tourProviderWeb: "https://heritagejourney.com",
      schedule: [
        ["6:00 AM: Arrival and hotel check-in", "9:00 AM: Trang An boat tour", "3:00 PM: Visit Bai Dinh Pagoda"],
        ["8:00 AM: Explore Thung Nham Bird Garden", "12:00 PM: Lunch at local restaurant", "4:00 PM: Sunset at Mua Caves"],
        ["7:00 AM: Visit Van Long Nature Reserve", "1:00 PM: Lunch and relaxation", "3:00 PM: Cycling tour around Ninh Binh"],
        ["8:00 AM: Breakfast and check-out", "11:00 AM: Departure"],
      ],
      imageUrl: "https://vnpay.vn/s1/statics.vnpay.vn/2023/11/0fsipq285igo1700281537310.png",
    ),
    Tour(
      destination: "Trang An",
      location: "Ninh Binh, Vietnam",
      days: 1,
      nights: 0,
      price: 70,
      tourProvider: "Quick Escape Tours",
      tourProviderWeb: "https://quickescapetours.com",
      schedule: [
        ["8:00 AM: Pick-up from Hanoi", "10:00 AM: Visit Trang An Complex", "2:00 PM: Boat ride in Tam Coc", "5:00 PM: Return to Hanoi"],
      ],
      imageUrl: "https://baothanhhoa.vn/media/mobile/news/2312/195d4154423t4810l3-1.jpg",
    ),
    Tour(
      destination: "Trang An",
      location: "Ninh Binh, Vietnam",
      days: 5,
      nights: 4,
      price: 300,
      tourProvider: "Vietnam Scenic Tours",
      tourProviderWeb: "https://vietnamscenictours.com",
      schedule: [
        ["7:00 AM: Arrival and hotel check-in", "10:00 AM: Boat trip in Trang An", "3:00 PM: Visit Bai Dinh Pagoda"],
        ["8:00 AM: Explore Cuc Phuong National Park", "12:00 PM: Lunch at local restaurant", "4:00 PM: Trekking in the park"],
        ["9:00 AM: Visit Hoa Lu Ancient Capital", "2:00 PM: Relaxation at hotel spa"],
        ["7:00 AM: Cycling tour to Tam Coc", "11:00 AM: Local market visit", "4:00 PM: Sunset at Mua Caves"],
        ["8:00 AM: Breakfast and hotel check-out", "10:00 AM: Departure"],
      ],
      imageUrl: "https://vissaihotel.vn/photo/khu-du-lich-trang-an-ninh-binh-co-gi-2.jpg",
    ),
    Tour(
      destination: "Hạ Long Bay",
      location: "Quang Ninh, Vietnam",
      days: 3,
      nights: 2,
      price: 130,
      tourProvider: "Vietnam Explorer",
      tourProviderWeb: "https://vietnamexplorer.com",
      schedule: [
        ["7:30 AM: Depart from Hanoi", "11:00 AM: Check-in at the hotel", "2:00 PM: Explore Ha Long Bay by cruise", "6:30 PM: Dinner on the cruise"],
        ["8:00 AM: Visit Thien Cung Cave", "10:00 AM: Swim at Bai Chay Beach", "12:00 PM: Lunch at a local restaurant", "3:00 PM: Shop for Ha Long specialties"],
        ["8:00 AM: Breakfast at the hotel", "9:00 AM: Return to Hanoi"],
      ],
      imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5SpfqOAFzZ3O3_3EvX3oTvdsT1Cr7VUjo_Q&s',
    ),
    Tour(
      destination: "Hạ Long Bay",
      location: "Quang Ninh, Vietnam",
      days: 4,
      nights: 3,
      price: 330,
      tourProvider: "Vietnam Alotour",
      tourProviderWeb: "https://vietnamalotour.com",
      schedule: [
        ["7:30 AM: Depart from Hanoi", "11:00 AM: Check-in at the hotel", "2:00 PM: Explore Ha Long Bay by cruise", "6:30 PM: Dinner on the cruise"],
        ["8:00 AM: Visit Thien Cung Cave", "10:00 AM: Swim at Bai Chay Beach", "12:00 PM: Lunch at a local restaurant", "3:00 PM: Shop for Ha Long specialties"],
        ["8:00 AM: Visit Thien Cung Cave", "10:00 AM: Swim at Bai Chay Beach", "12:00 PM: Lunch at a local restaurant", "3:00 PM: Shop for Ha Long specialties"],
        ["8:00 AM: Breakfast at the hotel", "9:00 AM: Return to Hanoi"],
      ],
      imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5SpfqOAFzZ3O3_3EvX3oTvdsT1Cr7VUjo_Q&s',
    ),
    Tour(
      destination: "Hạ Long Bay",
      location: "Quang Ninh, Vietnam",
      days: 3,
      nights: 2,
      price: 230,
      tourProvider: "Vietnam Trekker",
      tourProviderWeb: "https://vietnamtrekker.com",
      schedule: [
        ["7:30 AM: Depart from HCM City", "11:00 AM: Check-in at the hotel", "2:00 PM: Explore Ha Long Bay by cruise", "6:30 PM: Dinner on the cruise"],
        ["8:00 AM: Visit Thien Cung Cave", "10:00 AM: Swim at Bai Chay Beach", "12:00 PM: Lunch at a local restaurant", "3:00 PM: Shop for Ha Long specialties"],
        ["8:00 AM: Breakfast at the hotel", "9:00 AM: Return to Hanoi"],
      ],
      imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5SpfqOAFzZ3O3_3EvX3oTvdsT1Cr7VUjo_Q&s',
    ),
    Tour(
      destination: "Da Nang",
      location: "Da Nang, Vietnam",
      days: 4,
      nights: 3,
      price: 190,
      tourProvider: "Saigon Travel",
      tourProviderWeb: "https://saigontravel.com",
      schedule: [
        ["7:00 AM: Pickup at the airport", "9:30 AM: Hotel check-in", "2:00 PM: Visit Marble Mountains", "7:00 PM: Dinner in Hoi An Ancient Town"],
        ["7:00 AM: Depart for Ba Na Hills", "9:00 AM: Experience Golden Bridge", "12:00 PM: Buffet lunch at the summit", "3:00 PM: Enjoy Fantasy Park"],
        ["8:00 AM: Swim at My Khe Beach", "10:00 AM: Shop at Con Market", "2:00 PM: Visit Dragon Bridge and Han River Bridge"],
        ["7:00 AM: Breakfast at the hotel", "10:00 AM: Check-out and return home"],
      ],
      imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSY7yb5Ki_KWzCekqLcpZLR7PyG0Sd7jrWag&s',
    ),
    Tour(
        destination: "Nha Trang",
        location: "Khanh Hoa, Vietnam",
        days: 3,
        nights: 2,
        price: 150,
        tourProvider: "Viet Travel",
        tourProviderWeb: "https://viettravel.com",
        schedule: [
          ["8:00 AM: Pickup at Cam Ranh Airport", "11:00 AM: Hotel check-in", "2:00 PM: Visit Ponagar Towers", "6:30 PM: Seafood dinner at a local restaurant"],
          ["7:30 AM: Explore VinWonders", "10:00 AM: Ride the sea-crossing cable car", "12:00 PM: Lunch at VinWonders", "4:00 PM: Swim at Hon Tam Beach"],
          ["8:00 AM: Breakfast at the hotel", "10:00 AM: Check-out and shop at Dam Market", "12:00 PM: Return to the airport"],
        ],
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-J6wFA2iVZAVyeFTcTR-0XxvxxnvkWRkjbA&s'
    ),
    Tour(
        destination: "Da Lat",
        location: "Lam Dong, Vietnam",
        days: 3,
        nights: 2,
        price: 120,
        tourProvider: "Fiditour",
        tourProviderWeb: "https://fiditour.com",
        schedule: [
          ["6:30 AM: Depart from Ho Chi Minh City", "12:00 PM: Check-in at Da Lat", "2:00 PM: Visit Valley of Love", "6:00 PM: Dinner at a local restaurant"],
          ["8:00 AM: Explore Cau Dat Tea Hill", "11:00 AM: Visit Truc Lam Zen Monastery", "2:00 PM: Walk around Xuan Huong Lake", "5:00 PM: Enjoy local BBQ specialties"],
          ["8:00 AM: Shop at Da Lat Market", "10:00 AM: Check-out and return to Ho Chi Minh City"],
        ],
        imageUrl: 'https://cdn3.ivivu.com/2023/10/du-lich-Da-Lat-ivivu1.jpg'
    ),
    Tour(
        destination: "Phu Quoc",
        location: "Kien Giang, Vietnam",
        days: 5,
        nights: 4,
        price: 300,
        tourProvider: "Paradise Tours",
        tourProviderWeb: "https://paradisetours.com",
        schedule: [
          ["8:00 AM: Pickup at Phu Quoc Airport", "11:00 AM: Resort check-in", "2:00 PM: Visit VinWonders", "6:00 PM: Dinner by the beach"],
          ["7:30 AM: Explore Phu Quoc Safari", "12:00 PM: Lunch at Safari", "2:00 PM: Swim at Sao Beach", "7:00 PM: Fresh seafood dinner"],
          ["8:00 AM: Visit Ham Ninh Fishing Village", "11:00 AM: Tour Phu Quoc Fish Sauce Factory", "3:00 PM: Explore Dinh Cau Night Market"],
          ["8:00 AM: Fishing on the sea", "11:00 AM: Lunch on the boat", "4:00 PM: Sunset at Sunset Sanato"],
          ["8:00 AM: Breakfast at the resort", "10:00 AM: Check-out and transfer to the airport"],
        ],
        imageUrl: 'https://vcdn1-dulich.vnecdn.net/2022/04/08/dulichPhuQuoc-1649392573-9234-1649405369.jpg?w=0&h=0&q=100&dpr=2&fit=crop&s=SU6n3IvJxW1Sla0xqg31Kg'
    ),
    Tour(
      destination: "Hue Citadel",
      location: "Thua Thien Hue, Vietnam",
      days: 3,
      nights: 2,
      price: 150,
      tourProvider: "Hue Heritage Travel",
      tourProviderWeb: "https://hueheritagetravel.com",
      schedule: [
        ["9:00 AM: Visit Imperial City", "12:00 PM: Lunch at local restaurant", "3:00 PM: Explore Thien Mu Pagoda"],
        ["8:00 AM: Boat trip on Perfume River", "11:00 AM: Visit Tomb of Minh Mang", "5:00 PM: Evening at Dong Ba Market"],
        ["8:00 AM: Breakfast and check-out", "10:00 AM: Transfer to airport"],
      ],
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4-Z58WRYGZ06TFeGB2uKEk3bE5uEcJOiV9g&s",
    ),
    Tour(
      destination: "Hue Citadel",
      location: "Thua Thien Hue, Vietnam",
      days: 4,
      nights: 3,
      price: 200,
      tourProvider: "VietFun Tours",
      tourProviderWeb: "https://vietfun.com",
      schedule: [
        ["10:00 AM: Pickup and Imperial City tour", "1:00 PM: Lunch at local restaurant", "3:00 PM: Explore Khai Dinh Tomb"],
        ["7:30 AM: Visit Thanh Toan Bridge", "11:00 AM: Relax at Lap An Lagoon", "7:00 PM: Dinner with Hue cuisine"],
        ["8:30 AM: Visit Phu Cam Church", "12:00 PM: Shopping at Dong Ba Market", "6:00 PM: Royal dinner"],
        ["7:00 AM: Breakfast at the hotel", "9:00 AM: Transfer to airport"],
      ],
      imageUrl: "https://media-cdn.tripadvisor.com/media/photo-c/1280x250/0f/b4/dd/eb/hue-imperial-city-citadel.jpg",
    ),
    Tour(
      destination: "Hue Citadel",
      location: "Thua Thien Hue, Vietnam",
      days: 2,
      nights: 1,
      price: 120,
      tourProvider: "Asia Discovery",
      tourProviderWeb: "https://asiadiscovery.com",
      schedule: [
        ["8:00 AM: Pickup from Da Nang", "11:00 AM: Visit the Imperial City", "5:00 PM: Sunset at Tam Giang Lagoon"],
        ["7:30 AM: Explore Hue local market", "10:00 AM: Check-out and transfer"],
      ],
      imageUrl: "https://i.ytimg.com/vi/m7SVwJ8Fmek/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA3nDsqU3gn0EGpgvqN8xh6wBd0xg",
    ),
    Tour(
      destination: "Hue Citadel",
      location: "Thua Thien Hue, Vietnam",
      days: 2,
      nights: 1,
      price: 130,
      tourProvider: "Heritage Journey",
      tourProviderWeb: "https://heritagejourney.com",
      schedule: [
        ["9:00 AM: Arrival at Hue Citadel", "11:00 AM: Visit the Ngo Mon Gate and Thai Hoa Palace", "3:00 PM: Boat ride on the Perfume River", "7:00 PM: Dinner at a local restaurant"],
        ["8:00 AM: Guided tour of the Tomb of Emperor Minh Mang", "12:00 PM: Lunch at a garden house restaurant", "3:00 PM: Departure"],
      ],
      imageUrl: "https://static.kinhtedothi.vn/w960/images/upload/2022/11/06/trinh-dien-ao-dai-tai-cung-dinh-hue.jpg",
    ),

    Tour(
      destination: "Hue Citadel",
      location: "Thua Thien Hue, Vietnam",
      days: 3,
      nights: 2,
      price: 200,
      tourProvider: "Culture Trails",
      tourProviderWeb: "https://culturetrails.com",
      schedule: [
        ["8:00 AM: Pickup from Hue Airport", "10:30 AM: Explore the Imperial City", "3:00 PM: Visit Dong Ba Market", "7:30 PM: Night performance of Hue traditional music"],
        ["9:00 AM: Visit the Royal Tomb of Khai Dinh", "12:00 PM: Lunch at a traditional Hue restaurant", "2:30 PM: Tour of Tu Hieu Pagoda"],
        ["7:30 AM: Morning walk at Trang Tien Bridge", "9:00 AM: Breakfast and departure"],
      ],
      imageUrl: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/7a/57/7b/vue-interieure.jpg?w=500&h=500&s=1",
    ),

    Tour(
      destination: "Hue Citadel",
      location: "Thua Thien Hue, Vietnam",
      days: 4,
      nights: 3,
      price: 300,
      tourProvider: "Vietnam Insight Tours",
      tourProviderWeb: "https://vietnaminsighttours.com",
      schedule: [
        ["9:00 AM: Arrival and check-in at a riverside hotel", "11:00 AM: Tour the Forbidden Purple City", "5:00 PM: Sunset cruise on the Perfume River"],
        ["8:00 AM: Day trip to Bach Ma National Park", "1:00 PM: Picnic lunch", "5:00 PM: Return to hotel"],
        ["8:30 AM: Visit the Tomb of Emperor Tu Duc", "12:00 PM: Enjoy Hue Royal Cuisine lunch", "3:00 PM: Free time for souvenir shopping"],
        ["7:30 AM: Breakfast at the hotel", "9:00 AM: Departure"],
      ],
      imageUrl: "https://huesmiletravel.com.vn/wp-content/uploads/2024/05/Cac-tour-du-lich-hue-1-scaled.jpg",
    ),

    Tour(
      destination: "Hue Citadel",
      location: "Thua Thien Hue, Vietnam",
      days: 1,
      nights: 0,
      price: 75,
      tourProvider: "Quick Getaway Tours",
      tourProviderWeb: "https://quickgetawaytours.com",
      schedule: [
        ["8:00 AM: Pickup from Da Nang", "10:30 AM: Guided tour of the Imperial City", "1:00 PM: Lunch at a local restaurant", "3:00 PM: Visit Thien Mu Pagoda", "5:30 PM: Return to Da Nang"],
      ],
      imageUrl: "https://huedailytour.net/wp-content/uploads/2023/02/DAI-NOI.jpeg",
    ),

    Tour(
      destination: "Sa Pa",
      location: "Lao Cai, Vietnam",
      days: 3,
      nights: 2,
      price: 180,
      tourProvider: "Mountain Adventures",
      tourProviderWeb: "https://mountainadventures.com",
      schedule: [
        ["7:00 AM: Arrival and check-in", "10:00 AM: Visit Cat Cat Village", "3:00 PM: Trek to Muong Hoa Valley"],
        ["8:00 AM: Explore Fansipan Mountain", "12:00 PM: Lunch at local restaurant", "2:00 PM: Visit Ta Phin Village"],
        ["9:00 AM: Breakfast and check-out", "11:00 AM: Free time and transfer to train station"],
      ],
      imageUrl: "https://booking.muongthanh.com/upload_images/images/H%60/sa-pa-thi-tran-trong-suong.jpg",
    ),
    Tour(
      destination: "Sa Pa",
      location: "Lao Cai, Vietnam",
      days: 2,
      nights: 1,
      price: 150,
      tourProvider: "Trek Vietnam",
      tourProviderWeb: "https://trekvietnam.com",
      schedule: [
        ["6:00 AM: Arrival in Sapa", "9:00 AM: Check-in and explore local market", "3:00 PM: Trek to Silver Waterfall"],
        ["7:00 AM: Breakfast and Fansipan cable car", "11:00 AM: Check-out and transfer"],
      ],
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGAnVqnO8zkijib-B1CuiRqVHSG3U6ULiqDQ&s",
    ),
    Tour(
      destination: "Sa Pa",
      location: "Lao Cai, Vietnam",
      days: 4,
      nights: 3,
      price: 250,
      tourProvider: "Green Trekking",
      tourProviderWeb: "https://greentrekking.com",
      schedule: [
        ["6:30 AM: Arrival and hotel check-in", "10:00 AM: Visit Love Waterfall", "3:00 PM: Trek to Lao Chai Village"],
        ["8:00 AM: Explore Fansipan Mountain", "1:00 PM: Lunch and rest", "5:00 PM: Evening tour to Ta Van Village"],
        ["7:00 AM: Visit O Quy Ho Pass", "11:00 AM: Explore local ethnic market"],
        ["8:30 AM: Breakfast and check-out", "10:00 AM: Departure"],
      ],
      imageUrl: "https://media.thanhtra.com.vn/public/data/images/0/2020/12/31/congdinh/01.jpg?w=1319",
    ),
    Tour(
      destination: "Sa Pa",
      location: "Lao Cai, Vietnam",
      days: 3,
      nights: 2,
      price: 180,
      tourProvider: "Mountain Adventures",
      tourProviderWeb: "https://mountainadventures.com",
      schedule: [
        ["7:00 AM: Arrival and check-in", "10:00 AM: Visit Cat Cat Village", "3:00 PM: Trek to Muong Hoa Valley"],
        ["8:00 AM: Explore Fansipan Mountain", "12:00 PM: Lunch at local restaurant", "2:00 PM: Visit Ta Phin Village"],
        ["9:00 AM: Breakfast and check-out", "11:00 AM: Free time and transfer to train station"],
      ],
      imageUrl: "https://booking.muongthanh.com/upload_images/images/H%60/sa-pa-thi-tran-trong-suong.jpg",
    ),

    Tour(
      destination: "Sa Pa",
      location: "Lao Cai, Vietnam",
      days: 2,
      nights: 1,
      price: 150,
      tourProvider: "Highland Explorers",
      tourProviderWeb: "https://highlandexplorers.com",
      schedule: [
        ["6:30 AM: Pickup from Lao Cai", "10:00 AM: Tour through Silver Waterfall", "1:00 PM: Lunch in Sa Pa town", "3:00 PM: Visit Ham Rong Mountain"],
        ["8:00 AM: Trek to Lao Chai and Ta Van villages", "1:00 PM: Lunch at a homestay", "3:00 PM: Return to Sa Pa for departure"],
      ],
      imageUrl: "https://vcdn1-dulich.vnecdn.net/2022/05/10/san-tuyet-Sa-Pa-mobile-8770-16-5219-5180-1652148659.jpg?w=0&h=0&q=100&dpr=1&fit=crop&s=Z0OAdG5dyH1J7_hOp3DfKg",
    ),

    Tour(
      destination: "Sa Pa",
      location: "Lao Cai, Vietnam",
      days: 4,
      nights: 3,
      price: 250,
      tourProvider: "Nature Escapes",
      tourProviderWeb: "https://natureescapes.com",
      schedule: [
        ["7:00 AM: Arrival and check-in at a mountain lodge", "10:00 AM: Guided tour of Cat Cat Village", "2:00 PM: Visit Muong Hoa Valley", "6:00 PM: Dinner at the lodge"],
        ["8:00 AM: Cable car to Fansipan Peak", "1:00 PM: Picnic lunch", "3:00 PM: Visit Ban Ho Village"],
        ["7:30 AM: Breakfast at the lodge", "9:00 AM: Trek to Y Linh Ho Village", "1:00 PM: Lunch at a local restaurant", "5:00 PM: Free time in Sa Pa town"],
        ["8:00 AM: Breakfast and check-out", "10:00 AM: Departure"],
      ],
      imageUrl: "https://media.baobinhphuoc.com.vn/upload/news/5_2023/c29efc89b1a8554f27a79a5bf6bdf6a0.jpg",
    ),

    Tour(
      destination: "Sa Pa",
      location: "Lao Cai, Vietnam",
      days: 1,
      nights: 0,
      price: 100,
      tourProvider: "Quick Trek Tours",
      tourProviderWeb: "https://quicktrektours.com",
      schedule: [
        ["6:00 AM: Pickup from Lao Cai", "8:00 AM: Trek through Ta Phin Village", "12:00 PM: Lunch in Sa Pa town", "2:00 PM: Explore Love Waterfall", "5:00 PM: Return to Lao Cai"],
      ],
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcdqU1IIXrwcfDQDhPAd4pOKIH6K9qEFiiQA&s",
    ),

    Tour(
      destination: "Sa Pa",
      location: "Lao Cai, Vietnam",
      days: 5,
      nights: 4,
      price: 350,
      tourProvider: "Heritage Trails",
      tourProviderWeb: "https://heritagetrails.com",
      schedule: [
        ["7:00 AM: Arrival and check-in", "9:00 AM: Visit Cat Cat Village and Muong Hoa Valley", "6:00 PM: Traditional dinner"],
        ["8:00 AM: Trek to Ta Van Village", "12:00 PM: Lunch with local families", "3:00 PM: Visit Giang Ta Chai Village"],
        ["7:30 AM: Breakfast at the hotel", "9:00 AM: Explore Silver Waterfall and Love Waterfall", "1:00 PM: Lunch at Sa Pa town", "3:00 PM: Visit Fansipan Cable Car Station"],
        ["9:00 AM: Free morning for shopping in Sa Pa market", "12:00 PM: Lunch and rest", "2:00 PM: Visit local handicraft workshops"],
        ["8:00 AM: Breakfast and check-out", "10:00 AM: Departure"],
      ],
      imageUrl: "https://digishop.vnpt.vn/digitalShop/images/news/1701250627937xanh%20sapa.jpg",
    ),

    Tour(
      destination: "Phu Quoc",
      location: "Kien Giang, Vietnam",
      days: 3,
      nights: 2,
      price: 220,
      tourProvider: "Island Retreats",
      tourProviderWeb: "https://islandretreats.com",
      schedule: [
        ["9:00 AM: Arrival at Phu Quoc Airport", "11:00 AM: Hotel check-in", "2:00 PM: Explore VinWonders"],
        ["8:00 AM: Visit Phu Quoc Safari", "12:00 PM: Lunch at Safari Park", "3:00 PM: Relax at Sao Beach"],
        ["7:30 AM: Breakfast at the resort", "10:00 AM: Check-out and departure"],
      ],
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS71Pdtz6T82B25SU0B8P4dcD0UcQqWY14Ruw&s",
    ),
    Tour(
      destination: "Phu Quoc",
      location: "Kien Giang, Vietnam",
      days: 4,
      nights: 3,
      price: 300,
      tourProvider: "Paradise Tours",
      tourProviderWeb: "https://paradisetours.com",
      schedule: [
        ["7:00 AM: Arrival at Phu Quoc", "10:00 AM: Check-in at the resort", "3:00 PM: Explore Dinh Cau Night Market"],
        ["9:00 AM: Visit Ham Ninh Fishing Village", "12:00 PM: Fresh seafood lunch", "3:00 PM: Tour Phu Quoc Pearl Farm"],
        ["8:00 AM: Snorkeling at Hon Thom", "1:00 PM: Lunch on the boat", "5:00 PM: Sunset at Sunset Sanato"],
        ["7:30 AM: Breakfast at the hotel", "10:00 AM: Departure"],
      ],
      imageUrl: "https://laverandaresorts.com/wp-content/uploads/2020/04/0416-AJS-La-Veranda-Resort-Phu-Quoc-9339-copy.jpg",
    ),
    Tour(
      destination: "Phu Quoc",
      location: "Kien Giang, Vietnam",
      days: 5,
      nights: 4,
      price: 350,
      tourProvider: "Luxury Island Tours",
      tourProviderWeb: "https://luxuryislandtours.com",
      schedule: [
        ["6:30 AM: Flight to Phu Quoc", "9:00 AM: Check-in at luxury resort", "3:00 PM: Relaxation at the private beach"],
        ["7:00 AM: Island hopping tour", "12:00 PM: Barbecue lunch on the boat", "4:00 PM: Explore Hon Mot Island"],
        ["9:00 AM: Visit Phu Quoc National Park", "12:00 PM: Picnic lunch", "3:00 PM: Learn about Fish Sauce production"],
        ["8:00 AM: Shopping at Duong Dong Market", "2:00 PM: Visit Starfish Beach"],
        ["7:30 AM: Breakfast and check-out", "10:00 AM: Departure"],
      ],
      imageUrl: "https://laverandaresorts.com/wp-content/uploads/2020/04/0416-AJS-La-Veranda-Resort-Phu-Quoc-9339-copy.jpg",
    ),
    Tour(
      destination: "Phu Quoc",
      location: "Kien Giang, Vietnam",
      days: 2,
      nights: 1,
      price: 150,
      tourProvider: "Quick Getaway",
      tourProviderWeb: "https://quickgetaway.com",
      schedule: [
        ["8:00 AM: Arrival at Phu Quoc", "10:00 AM: Tour Phu Quoc Night Market", "3:00 PM: Sunset at Long Beach"],
        ["8:30 AM: Visit Coconut Prison", "12:00 PM: Lunch and departure"],
      ],
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqQ0D_ivNk90KAWN2p8Oz3yM79FHj_mjpKNg&s",
    ),
    Tour(
      destination: "Hoi An",
      location: "Quang Nam, Vietnam",
      days: 3,
      nights: 2,
      price: 250,
      tourProvider: "Heritage Adventures",
      tourProviderWeb: "https://heritageadventures.com",
      schedule: [
        ["8:00 AM: Arrival in Hoi An", "11:00 AM: Check-in at the hotel", "3:00 PM: Walking tour of Hoi An Ancient Town", "7:00 PM: Lantern boat ride on the Thu Bon River"],
        ["9:00 AM: Visit Tra Que Vegetable Village", "12:00 PM: Vietnamese cooking class and lunch", "3:00 PM: Explore An Bang Beach", "6:30 PM: Dinner at a riverside restaurant"],
        ["7:30 AM: Breakfast at the hotel", "9:00 AM: Visit My Son Sanctuary", "12:00 PM: Departure"],
      ],
      imageUrl: "https://imagev3-lang.vietnamplus.vn/w1000/Uploaded_EN/sxtt/2023_08_21/hoian.jpg.webp",
    ),

    Tour(
      destination: "Hoi An",
      location: "Quang Nam, Vietnam",
      days: 5,
      nights: 4,
      price: 450,
      tourProvider: "Golden Lantern Travel",
      tourProviderWeb: "https://goldenlanterntravel.com",
      schedule: [
        ["8:00 AM: Arrival in Hoi An", "10:00 AM: Check-in at the resort", "2:00 PM: Explore Hoi An Ancient Town", "7:30 PM: Night market shopping and street food tasting"],
        ["8:00 AM: Visit the Cam Thanh Coconut Village", "11:00 AM: Basket boat ride through the waterways", "2:00 PM: Relax at Cua Dai Beach", "6:00 PM: Seafood dinner at the beach"],
        ["9:00 AM: Bicycle tour to local villages", "12:00 PM: Lunch with a local family", "3:00 PM: Learn traditional lantern making"],
        ["8:00 AM: Visit Marble Mountains", "12:00 PM: Lunch at a Da Nang riverside restaurant", "4:00 PM: Back to Hoi An for free exploration"],
        ["7:30 AM: Breakfast at the resort", "10:00 AM: Departure"],
      ],
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkgcToAx4SzXYsbOkVD7w0nEowq15v7-MWBQ&s",
    ),

    Tour(
      destination: "Hoi An",
      location: "Quang Nam, Vietnam",
      days: 2,
      nights: 1,
      price: 180,
      tourProvider: "Hoi An Highlights",
      tourProviderWeb: "https://hoianhighlights.com",
      schedule: [
        ["9:00 AM: Arrival in Hoi An", "11:00 AM: Guided tour of Hoi An Ancient Town", "2:00 PM: Visit a local tailor shop", "6:00 PM: Dinner at a traditional restaurant"],
        ["7:30 AM: Breakfast at the hotel", "9:00 AM: Boat ride to Cham Island", "1:00 PM: Departure"],
      ],
      imageUrl: "https://images.vietnamtourism.gov.vn/vn/images/2021/anh_hoi_an2.jpg",
    ),
    Tour(
      destination: "Hoi An",
      location: "Quang Nam, Vietnam",
      days: 4,
      nights: 3,
      price: 320,
      tourProvider: "Cultural Wonders Travel",
      tourProviderWeb: "https://culturalwonderstravel.com",
      schedule: [
        ["8:00 AM: Arrival in Hoi An", "10:00 AM: Check-in at the boutique hotel", "3:00 PM: Explore Japanese Covered Bridge and Old House of Tan Ky"],
        ["7:30 AM: Breakfast at the hotel", "9:00 AM: Boat ride to Kim Bong Carpentry Village", "12:30 PM: Traditional lunch with local artisans", "3:00 PM: Free time for shopping and sightseeing"],
        ["8:30 AM: Visit Thanh Ha Pottery Village", "12:00 PM: Vietnamese street food lunch", "4:00 PM: Enjoy the sunset at Hoi An Memories Island Show"],
        ["7:00 AM: Morning stroll along Thu Bon River", "9:00 AM: Departure"],
      ],
      imageUrl: "https://congdankhuyenhoc.qltns.mediacdn.vn/449484899827462144/2023/4/6/11125-quang-nam-huybankgmailcom-hoi-an-ve-dem--1680754661887922764789.jpg",
    ),

    Tour(
      destination: "Hoi An",
      location: "Quang Nam, Vietnam",
      days: 3,
      nights: 2,
      price: 270,
      tourProvider: "Nature Escape Tours",
      tourProviderWeb: "https://natureescapetours.com",
      schedule: [
        ["9:00 AM: Arrival and transfer to eco-lodge", "11:00 AM: Check-in and welcome drinks", "3:00 PM: Cycling tour through rice paddies", "7:00 PM: Vietnamese dinner under the stars"],
        ["8:00 AM: Guided trekking in Ba Na Hills", "12:00 PM: Picnic lunch", "3:00 PM: Relax at the eco-lodge spa"],
        ["7:00 AM: Breakfast at the lodge", "9:00 AM: Visit the Hoi An Silk Village", "12:00 PM: Departure"],
      ],
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7LH9LisG_kOtN2Ahn9ZwRXTMlG082KLb0EQ&s",
    ),

    Tour(
      destination: "Hoi An",
      location: "Quang Nam, Vietnam",
      days: 5,
      nights: 4,
      price: 480,
      tourProvider: "Lux Travel Vietnam",
      tourProviderWeb: "https://luxtravelvietnam.com",
      schedule: [
        ["8:00 AM: Arrival in Hoi An", "10:00 AM: Transfer to luxury villa and check-in", "2:00 PM: Relax by the pool", "6:00 PM: Dinner at a Michelin-starred restaurant"],
        ["8:30 AM: Private boat tour on the Thu Bon River", "12:30 PM: Gourmet lunch aboard the boat", "4:00 PM: Visit to Hoi An Museum of History and Culture"],
        ["7:00 AM: Visit My Son Sanctuary", "12:00 PM: Return for lunch at the villa", "5:00 PM: Personalized lantern-making workshop"],
        ["9:00 AM: Explore nearby Cham Island with snorkeling and seafood lunch", "4:00 PM: Return to villa for a private BBQ dinner"],
        ["8:00 AM: Breakfast in the garden", "10:00 AM: Departure"],
      ],
      imageUrl: "https://www.quangbinhtravel.vn/wp-content/uploads/2019/11/ph%E1%BB%91-c%E1%BB%95-h%E1%BB%99i-an-v%E1%BB%81-%C4%91em.gif",
    ),

  ];
}