import '../../models/Tour.dart';

class Data {
  static final toursData = [
    Tour(
      destination: "Hạ Long Bay",
      location: "Quang Ninh, Vietnam",
      days: 3,
      nights: 2,
      price: 130,
      tourProvider: "Vietnam Explorer",
      tourProviderWeb: "https://vietnamexplorer.com",
      schedule: [
        ["7:30 AM: Depart from Hanoi", "11:00 AM: Check-in at the hotel", "2:00 PM: Explore Ha Long Bay by cruise", "6:30 PM: Dinner on the cruise"],
        ["8:00 AM: Visit Thien Cung Cave", "10:00 AM: Swim at Bai Chay Beach", "12:00 PM: Lunch at a local restaurant", "3:00 PM: Shop for Ha Long specialties"],
        ["8:00 AM: Breakfast at the hotel", "9:00 AM: Return to Hanoi"],
      ],
      imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5SpfqOAFzZ3O3_3EvX3oTvdsT1Cr7VUjo_Q&s',
    ),
    Tour(
      destination: "Da Nang",
      location: "Da Nang, Vietnam",
      days: 4,
      nights: 3,
      price: 190,
      tourProvider: "Saigon Travel",
      tourProviderWeb: "https://saigontravel.com",
      schedule: [
        ["7:00 AM: Pickup at the airport", "9:30 AM: Hotel check-in", "2:00 PM: Visit Marble Mountains", "7:00 PM: Dinner in Hoi An Ancient Town"],
        ["7:00 AM: Depart for Ba Na Hills", "9:00 AM: Experience Golden Bridge", "12:00 PM: Buffet lunch at the summit", "3:00 PM: Enjoy Fantasy Park"],
        ["8:00 AM: Swim at My Khe Beach", "10:00 AM: Shop at Con Market", "2:00 PM: Visit Dragon Bridge and Han River Bridge"],
        ["7:00 AM: Breakfast at the hotel", "10:00 AM: Check-out and return home"],
      ],
      imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSY7yb5Ki_KWzCekqLcpZLR7PyG0Sd7jrWag&s',
    ),
    Tour(
        destination: "Nha Trang",
        location: "Khanh Hoa, Vietnam",
        days: 3,
        nights: 2,
        price: 150,
        tourProvider: "Viet Travel",
        tourProviderWeb: "https://viettravel.com",
        schedule: [
          ["8:00 AM: Pickup at Cam Ranh Airport", "11:00 AM: Hotel check-in", "2:00 PM: Visit Ponagar Towers", "6:30 PM: Seafood dinner at a local restaurant"],
          ["7:30 AM: Explore VinWonders", "10:00 AM: Ride the sea-crossing cable car", "12:00 PM: Lunch at VinWonders", "4:00 PM: Swim at Hon Tam Beach"],
          ["8:00 AM: Breakfast at the hotel", "10:00 AM: Check-out and shop at Dam Market", "12:00 PM: Return to the airport"],
        ],
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-J6wFA2iVZAVyeFTcTR-0XxvxxnvkWRkjbA&s'
    ),
    Tour(
        destination: "Da Lat",
        location: "Lam Dong, Vietnam",
        days: 3,
        nights: 2,
        price: 120,
        tourProvider: "Fiditour",
        tourProviderWeb: "https://fiditour.com",
        schedule: [
          ["6:30 AM: Depart from Ho Chi Minh City", "12:00 PM: Check-in at Da Lat", "2:00 PM: Visit Valley of Love", "6:00 PM: Dinner at a local restaurant"],
          ["8:00 AM: Explore Cau Dat Tea Hill", "11:00 AM: Visit Truc Lam Zen Monastery", "2:00 PM: Walk around Xuan Huong Lake", "5:00 PM: Enjoy local BBQ specialties"],
          ["8:00 AM: Shop at Da Lat Market", "10:00 AM: Check-out and return to Ho Chi Minh City"],
        ],
        imageUrl: 'https://cdn3.ivivu.com/2023/10/du-lich-Da-Lat-ivivu1.jpg'
    ),
    Tour(
        destination: "Phú Quốc",
        location: "Kien Giang, Vietnam",
        days: 5,
        nights: 4,
        price: 300,
        tourProvider: "Paradise Tours",
        tourProviderWeb: "https://paradisetours.com",
        schedule: [
          ["8:00 AM: Pickup at Phu Quoc Airport", "11:00 AM: Resort check-in", "2:00 PM: Visit VinWonders", "6:00 PM: Dinner by the beach"],
          ["7:30 AM: Explore Phu Quoc Safari", "12:00 PM: Lunch at Safari", "2:00 PM: Swim at Sao Beach", "7:00 PM: Fresh seafood dinner"],
          ["8:00 AM: Visit Ham Ninh Fishing Village", "11:00 AM: Tour Phu Quoc Fish Sauce Factory", "3:00 PM: Explore Dinh Cau Night Market"],
          ["8:00 AM: Fishing on the sea", "11:00 AM: Lunch on the boat", "4:00 PM: Sunset at Sunset Sanato"],
          ["8:00 AM: Breakfast at the resort", "10:00 AM: Check-out and transfer to the airport"],
        ],
        imageUrl: 'https://vcdn1-dulich.vnecdn.net/2022/04/08/dulichPhuQuoc-1649392573-9234-1649405369.jpg?w=0&h=0&q=100&dpr=2&fit=crop&s=SU6n3IvJxW1Sla0xqg31Kg'
    ),
    Tour(
      destination: "Hue",
      location: "Thua Thien Hue, Vietnam",
      days: 3,
      nights: 2,
      price: 150,
      tourProvider: "Hue Heritage Travel",
      tourProviderWeb: "https://hueheritagetravel.com",
      schedule: [
        ["9:00 AM: Visit Imperial City", "12:00 PM: Lunch at local restaurant", "3:00 PM: Explore Thien Mu Pagoda"],
        ["8:00 AM: Boat trip on Perfume River", "11:00 AM: Visit Tomb of Minh Mang", "5:00 PM: Evening at Dong Ba Market"],
        ["8:00 AM: Breakfast and check-out", "10:00 AM: Transfer to airport"],
      ],
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4-Z58WRYGZ06TFeGB2uKEk3bE5uEcJOiV9g&s",
    ),
    Tour(
      destination: "Hue",
      location: "Thua Thien Hue, Vietnam",
      days: 4,
      nights: 3,
      price: 200,
      tourProvider: "VietFun Tours",
      tourProviderWeb: "https://vietfun.com",
      schedule: [
        ["10:00 AM: Pickup and Imperial City tour", "1:00 PM: Lunch at local restaurant", "3:00 PM: Explore Khai Dinh Tomb"],
        ["7:30 AM: Visit Thanh Toan Bridge", "11:00 AM: Relax at Lap An Lagoon", "7:00 PM: Dinner with Hue cuisine"],
        ["8:30 AM: Visit Phu Cam Church", "12:00 PM: Shopping at Dong Ba Market", "6:00 PM: Royal dinner"],
        ["7:00 AM: Breakfast at the hotel", "9:00 AM: Transfer to airport"],
      ],
      imageUrl: "https://media-cdn.tripadvisor.com/media/photo-c/1280x250/0f/b4/dd/eb/hue-imperial-city-citadel.jpg",
    ),
    Tour(
      destination: "Hue",
      location: "Thua Thien Hue, Vietnam",
      days: 2,
      nights: 1,
      price: 120,
      tourProvider: "Asia Discovery",
      tourProviderWeb: "https://asiadiscovery.com",
      schedule: [
        ["8:00 AM: Pickup from Da Nang", "11:00 AM: Visit the Imperial City", "5:00 PM: Sunset at Tam Giang Lagoon"],
        ["7:30 AM: Explore Hue local market", "10:00 AM: Check-out and transfer"],
      ],
      imageUrl: "https://i.ytimg.com/vi/m7SVwJ8Fmek/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA3nDsqU3gn0EGpgvqN8xh6wBd0xg",
    ),

    // Tours for Sapa
    Tour(
      destination: "Sapa",
      location: "Lao Cai, Vietnam",
      days: 3,
      nights: 2,
      price: 180,
      tourProvider: "Mountain Adventures",
      tourProviderWeb: "https://mountainadventures.com",
      schedule: [
        ["7:00 AM: Arrival and check-in", "10:00 AM: Visit Cat Cat Village", "3:00 PM: Trek to Muong Hoa Valley"],
        ["8:00 AM: Explore Fansipan Mountain", "12:00 PM: Lunch at local restaurant", "2:00 PM: Visit Ta Phin Village"],
        ["9:00 AM: Breakfast and check-out", "11:00 AM: Free time and transfer to train station"],
      ],
      imageUrl: "https://booking.muongthanh.com/upload_images/images/H%60/sa-pa-thi-tran-trong-suong.jpg",
    ),
    Tour(
      destination: "Sapa",
      location: "Lao Cai, Vietnam",
      days: 2,
      nights: 1,
      price: 150,
      tourProvider: "Trek Vietnam",
      tourProviderWeb: "https://trekvietnam.com",
      schedule: [
        ["6:00 AM: Arrival in Sapa", "9:00 AM: Check-in and explore local market", "3:00 PM: Trek to Silver Waterfall"],
        ["7:00 AM: Breakfast and Fansipan cable car", "11:00 AM: Check-out and transfer"],
      ],
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGAnVqnO8zkijib-B1CuiRqVHSG3U6ULiqDQ&s",
    ),
    Tour(
      destination: "Sapa",
      location: "Lao Cai, Vietnam",
      days: 4,
      nights: 3,
      price: 250,
      tourProvider: "Green Trekking",
      tourProviderWeb: "https://greentrekking.com",
      schedule: [
        ["6:30 AM: Arrival and hotel check-in", "10:00 AM: Visit Love Waterfall", "3:00 PM: Trek to Lao Chai Village"],
        ["8:00 AM: Explore Fansipan Mountain", "1:00 PM: Lunch and rest", "5:00 PM: Evening tour to Ta Van Village"],
        ["7:00 AM: Visit O Quy Ho Pass", "11:00 AM: Explore local ethnic market"],
        ["8:30 AM: Breakfast and check-out", "10:00 AM: Departure"],
      ],
      imageUrl: "https://media.thanhtra.com.vn/public/data/images/0/2020/12/31/congdinh/01.jpg?w=1319",
    ),
  ];
}